### ISSUE TITLE
Biometry is broken after the app is resumed following closure using the hardware back button

### ISSUE THREAD

**Issue by KikkoMax** [nventive/BiometryService#27]
## Expected Behavior
Authentication should work once the app is resumed after closing the app using the hardware back button

## Actual Behavior
Authentication doesn't work once resumed, and button stays stuck

## Steps to Reproduce the Problem

1. Start sample android app
2. Minimize app by using hardware back button
3. Resume the app from the recent tasks hardware button
4. Click on the Authenticate button
5. Nothing happens, button becomes stuck
5. Check output for E/BiometricPromptCompat(24732): Unable to start authentication. Called after onSaveInstanceState().

## Specifications

- Version: 0.2.0-dev.67
- Platform: Android
- Subsystem: All

**Comment by Soap-141** [comment]
Package has been updated a lot since, you should try again and see if it's still an issue, sorry for the delay. Closing this issue.
