### ISSUE TITLE
[iOS] Decrypt returns null instead of throwing when FaceID permission was removed

### ISSUE THREAD

**Issue by jeanplevesque** [nventive/BiometryService#50]
## Expected Behavior

The service should throw when asked to do an action that is not supported in the current system state.

## Actual Behavior

![image](https://user-images.githubusercontent.com/39710855/145113696-95b8439d-1501-42d0-b28c-20acb2e9d696.png)

## Steps to Reproduce the Problem

1. Encrypt data using BiometryService on iOS.
2. Go to settings and remove the FaceID permission from the app.
3. Decrypt data using BiometryService.
4. Notice that `null` is returned instead of the service throwing an exception.

## Specifications

- Version:
- Platform: iOS
- Subsystem:

**Comment by Soap-141** [comment]
New behavior since refactor, closing this.
