### ISSUE TITLE
[Android] Exception when fingerprints changed is not explicit enough

### ISSUE THREAD

**Issue by jeanplevesque** [nventive/BiometryService#51]
## Expected Behavior

It should be a custom exception or an exception that contains an enum that strongly associate the error so that the app can take action (such as removing the invalid biometric configuration).

## Actual Behavior

![image](https://user-images.githubusercontent.com/39710855/145594970-ca13f295-e34c-4d78-8818-add4eda21728.png)

## Steps to Reproduce the Problem

1. Ensure you have a fingerprint configured on the device.
2. Use Encrypt.
3. Remove the fingerprint from the device.
4. Add a new fingerprint in the device.
5. Use Decrypt.
6. Notice a generic `ArgumentException`.

## Specifications

- Version:
- Platform: Android
- Subsystem:

**Comment by jeanplevesque** [comment]
@MatFillion @Iguins

**Comment by Soap-141** [comment]
New behavior since refactor, closing this.
